### ISSUE TITLE
Jenkins interface fails with error in build executor status frame.

### ISSUE THREAD

**Issue by DemenkovK** [jenkinsci/proxmox-plugin#12]
Jenkins interface fails with the error in build executor status frame, when reconnecting reverted slave:

> `Caught unhandled exception with ID 64a2d2f0-6b8b-4ff0-8407-3c88a61256eb
org.apache.commons.jelly.JellyTagException: jar:file:/var/cache/jenkins/war/WEB-INF/lib/jenkins-core-2.235.2.jar!/hudson/model/View/sidepanel.jelly:75:50: <st:include> org.apache.commons.jelly.JellyTagException: jar:file:/var/cache/jenkins/war/WEB-INF/lib/jenkins-core-2.235.2.jar!/lib/hudson/executors.jelly:41:68: <j:when> Failed to localize key=Disconnect before snapshot revert,args=[]`

**Comment by Maxhy** [comment]
Fixed with #13? (thanks @eugenyk)
