### ISSUE TITLE
Documentation is missing

### ISSUE THREAD

**Issue by bitchecker** [jenkinsci/proxmox-plugin#18]
## Summary

The only page marked as documentation is this [page](https://plugins.jenkins.io/proxmox/#documentation) but it doesn't cover any use case, requirements, and details on how to use it.

Could you please link some references?

**Comment by Maxhy** [comment]
I created https://github.com/jenkinsci/proxmox-plugin/wiki as a starting point but I'm not sure what kind of information you are requesting here.
This plugin is mainly about Proxmox node definition and management, agent connection running on the VM is then up to you (you will probably connect at boot or use a snapshot running jnlp instance, etc...). Let me know, thanks.

**Comment by bguerin** [comment]
Hello @Maxhy 

You have a typo on your wiki :
https://github.com/jenkinsci/proxmox-plugin/wiki#snapshotname---revert-snapshot

> The snapshot to revert the virtual machine **too** when it is started

I think the plugin should expose such help / documentation in Jenkins itself through help files. I will recheck my configuration but from what I remember revert policy, and delays are not so easy to understand at the first look

**Comment by tkriviradev** [comment]
Hello,

Sorry for my Dummy question, however is there a recommendation what connection plugin from the slave back to the jenkins we can use? 

Like for example in "vSphere plugin" they suggest ssh or "JNLP" + vmware-tools commands execution.

Thank you in advance.

**Comment by Maxhy** [comment]
This is no recommended connection plugin. I personally use JNLP for Windows machines and SSH for linux ones.
