### ISSUE TITLE
Update Jenkins repository plugin's

### ISSUE THREAD

**Issue by Morkxy** [jenkinsci/proxmox-plugin#8]
Hi,

This page is out of date:
https://wiki.jenkins.io/display/JENKINS/Proxmox+Plugin

It's the same in Jenkins pluginManager page (on Jenkins):
![image](https://user-images.githubusercontent.com/1465355/73076623-c5b67980-3ebe-11ea-82f7-f38f41e94fae.png)

Can you update this? Indeed, this GIT repository can propose more than "version 0.2.2" ! :)

**Comment by Maxhy** [comment]
Updated, released and published. Wiki page should be automatically refreshed over the night I believe.
